### ISSUE TITLE
Design element consistence for console

### ISSUE THREAD

**Issue by fgerschwiler** [caos/zitadel#3022]
With the console redesign we should have consistent elements.

**Acceptance criteria**
- [ ] Saving mechanism (e.g auto save, save button, pop up to save)
- [ ] Table actions (buttons on hover, always icons, how do de icons look like)
- [ ] Navigation
- [ ] Documentation links #1677 

Hier sind noch zusätzliche Findings die mir aufgefallen sind und in das Thema Consistency laufen: (siehe Kommentare unten für mehr Details)

- [ ]  table inconcistency
- [ ]  table edit mode
- [ ]  table deselect-button
- [ ]  table buttons activate/deactivate
- [ ]  log panel (right) consistency
- [ ]  _Question_: separate button modify

**Comment by fgerschwiler** [comment]
Estimate: 0.5d - 1d

**Comment by juergrinaldi** [comment]
**Saving Principles**
====

A) I suggest we switch to a complete 'auto save' system. All changes shall be auto saved and therefore no save buttons needed. 
To ensure the user that  the changes have been saved, we display a short toast message (see pic below) with the ability to undo the action.

![image](https://user-images.githubusercontent.com/48990649/150918820-a38d2ab8-2ab6-4901-955b-bd1f07eb86a6.png)

B) If 'auto save' can't be enabled, we use a 'save button' at the end of each section. We try to keep content in short sections whenever possible, so the save button is mostly visible at first glance. And it's very important that we stop the user from leaving the site if they have unsaved changes with a mandatory pop-up that asks for the input to either save or discard changes. (see pic below)
Also save buttons should only be active when there are unsaved changes. (example: Organization > Message Texts)

![image](https://user-images.githubusercontent.com/48990649/150919036-c0b1590c-4d3f-4d7e-b572-66ccefdf189f.png)


Table Actions
=============

Tables in general should be consistent. Right now we have several different looks (pics).

As for the table actions: 
A) on the table row is only an icon for actions (3 dots) with a context menu of all available actions. (see pics below)
![image](https://user-images.githubusercontent.com/48990649/150920888-6ef92e53-795b-42a6-b57f-ed1c7e4a2d53.png)
![image](https://user-images.githubusercontent.com/48990649/150921019-22ef4abd-3f21-4b34-a2ad-6a45096606ed.png)

B) as a second approach we have the select actions. if the user selects one or more rows in the table, available actions will be displayed as buttons in the top right of the table.
![image](https://user-images.githubusercontent.com/48990649/150922757-72e350f3-534a-443d-8aec-1c99ce9a9ce0.png)

If more than ~3 (depends on available space) are present, we use a Button 'More...' where again a context menu is presented. ![image](https://user-images.githubusercontent.com/48990649/150924683-551d95e2-390b-4e70-b868-85ef80e42086.png)


Navigation
=======

The Navigation is split up into 1st and 2nd-level. 1st level navigation is horizontally oriented. 2nd level is vertically left of the content. it is only used when there is a need for separate sections within the context of the content. 

1st level navigation always refers to the current organization. That's why there is no 1st level navigation on the user profile page and instead uses the 2nd level nav.

Disclaimer: Be aware that the horizontal navigation is only valid for a certain number of links. If - in the near future - we have to add more links, it might be necessary to change to a vertical orientiation.

On a sidenote:
it's possible to use 1st level at the current ammount of links. I think the current approach with 2nd level is more viable though and I'd stick to that.
![image](https://user-images.githubusercontent.com/48990649/150924897-32be3374-e8d3-4e10-954e-09fff359c9aa.png)


Deep Links Documentation
=================

My suggestion is already documented in #1677 
But to sum it up:
- use i-Icon wherever it's applicable. (It should be very versatile on where to put it)
- Display a short text description for a quick hint and...
- ...where needed provide a Button in the context menu with a deeplink to the doc (or other information page)
- optional: provide some contact links for further questions.

**Comment by juergrinaldi** [comment]
- [ ]  **Bug**: farbe BG wechselt

**Comment by juergrinaldi** [comment]
- [ ] **table edit mode**

**Comment by juergrinaldi** [comment]
- [ ]  **table deselect-button**

**Comment by juergrinaldi** [comment]
- [ ] **table buttons activate/deactivate**

**Comment by juergrinaldi** [comment]
- [ ] **log panel (right) consistency**

**Comment by juergrinaldi** [comment]
- [ ] **Question: separate button modify**
