### ISSUE TITLE
login screen: browser back breaks login

### ISSUE THREAD

**Issue by buehler** [caos/zitadel#403]
When logging in and using "browser back" (instead of the button) the frontend does not "go back". Instead the password screen is shown again. After inserting the password, another password screen is shown.

![login browser back](https://user-images.githubusercontent.com/1067213/87003186-75f11380-c1bb-11ea-91f5-3a6d30a4e240.gif)

steps to reproduce:
- to go login page
- enter email
- click next
- on password enter screen, use browser back (you'll land on the password screen instead of the email screen)
- enter password (and land on the password screen again)

**Comment by fgerschwiler** [comment]
we improved the login flow, added some back and cancel buttons where needed,
because we calculate login flow in the application you cant always go back. in this cases next logical step is rendered, (eg after mfa setup done, you cant go back to setup again, in this case you get to the verify otp step)
